source 'http://rubygems.org'

gem 'rails', '2.3.11'

gem 'active-fedora', '=2.3.7'
gem 'authlogic', '>=0.1.0'
gem 'builder'
gem 'columnize'
gem 'crack'
gem 'curb'
gem 'database_cleaner'
gem 'diff-lcs'
gem 'facets', '2.8.4'
gem 'haml'
gem 'httparty'
gem 'json_pure', '>1.4.3'
gem 'linecache'
gem 'marc'
gem 'mime-types'
gem 'multipart-post'
gem 'nokogiri', '1.4.4'
gem 'om', '>=1.0.1'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rcov'
gem 'RedCloth', '4.2.7'
gem 'rsolr', '=0.12.1'
gem 'rsolr-ext', '=0.12.1'
gem 'solr-ruby' 
gem 'solrizer', '>=1.1.1'
gem 'solrizer-fedora', '>=1.1.1'
gem 'stomp'
gem 'sqlite3-ruby', '1.2.5'
gem 'term-ansicolor'
gem 'trollop'
gem 'webrat'
gem 'will_paginate'
gem 'xml-simple'
gem 'yard'

gem 'rubytree'
gem 'rest-client'

source 'http://gemcutter.org'

gem 'block_helpers'

group :development, :test do
  gem 'ruby-debug'
  gem 'ruby-debug-base'
  gem 'rspec', '<2.0.0'  
  gem 'rspec-rails', '<2.0.0' # rspec-rails 2.0.0 requires Rails 3.
  gem 'mocha'
  gem 'cucumber', '>=0.8.5'
  gem 'cucumber-rails', '~> 0.3.2'  # cucumber-rail 0.4.0 and on requires Rails 3
  gem 'gherkin'
  gem 'jettywrapper'
end
