staff:
  - staff1
student
  - student1
archivist:
  - archivist1
  - archivist2
  - leland_himself
donor:
  - donor1
  - leland_himself
researcher:
  - researcher1
patron:
  - patron1
  - leland_himself
