staff:
  - staff1@example.com
student:
  - student1@example.com
archivist:
  - archivist1@example.com
  - archivist2@example.com
  - leland_himself@example.com
donor:
  - donor1@example.com
  - leland_himself@example.com
researcher:
  - researcher1@example.com
patron:
  - patron1@example.com
  - leland_himself@example.com
contentAccessTeam:
  - contentaccessteam1@example.com
