staff:
 - staff1@example.com
 - committeesection1@example.com
 - engineering1@example.com
student:
 - student1@example.com
committeeSection:
 - committeesection1@example.com
engineering:
 - engineering1@example.com
archivist:
  - archivist1@example.com
donor:
  - donor1@example.com
researcher:
  - researcher1@example.com
patron:
  - patron1@example.com
contentAccessTeam:
  - contentaccessaeam1@example.com
