staff:
 - staff1@example.com
 - committeeSection1@example.com
 - engineering1@example.com
student:
 - student1@example.com
committeeSection:
 - committeeSection1@example.com
engineering:
 - engineering1@example.com
contentAccessTeam:
  - contentAccessTeam1@example.com
