:service_mapping:
 "fedora-system:3":
   :object_profile: viewObjectProfile
   :method_index: viewMethodIndex
   :item_index: viewItemIndex
   :dc_view: viewDublinCore
 "hydra-sDef:commonMetadata":
   :oai_dc: getOAI_DC
 "hull-sDef:dataset":
   :datacite_metadata: getDataCiteMetadata

